<div class="row">
	<div class="col-md-12">
		<!-- BEGIN VALIDATION STATES-->
		<div class="portlet">
			<div class="portlet-title">
				<div class="caption">

					<i class="fa fa-gift"></i><?php echo $this->lang['admin_category_add_new']?>
                    
                </div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form action="<?php echo $this->baseUrl('admin/user/save')?>"
					id="admin_form" class="form-horizontal" method="POST">
					<div class="form-body">  
                        <?php if (count($this->messages)) : ?>
                            <?php foreach ($this->messages as $message) : ?>
                                <div class="alert alert-success">
							<button class="close" data-close="alert"></button>
                                    <?php echo $message; ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
							You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
							Your form validation is successful!
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Mật khẩu cũ <span
								class="required"> * </span>
							</label>
							<div class="col-md-4">
                                <?php echo $this->form->getElement('password_old')?>
                            </div>
						</div>

						<div class="form-group">
							<label class="control-label col-md-3">Mật khẩu mới </label>
							<div class="col-md-4">
                                <?php echo $this->form->getElement('password_new')?>
                            </div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Xác nhận mật khẩu </label>
							<div class="col-md-4">
                                <?php echo $this->form->getElement('password_confirm')?>
                            </div>
						</div>

					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<input type="hidden" name="access_redirect" value=""
									id="access_redirect" />
								<button type="submit" class="btn green" id="save">Lưu</button>
								<button type="submit" class="btn btn-info" id="save_and_close">Lưu
									và đóng</button>
								<button type="button" class="btn default"
									data-url="<?php echo $this->baseUrl('admin/index')?>"
									id="btn_cancel">Hủy</button>
							</div>
						</div>
					</div>
				</form>
				<!-- END FORM-->
			</div>
			<!-- END VALIDATION STATES-->
		</div>
	</div>
</div>
