<div class="row">
	<div class="col-md-12">
		<!-- BEGIN VALIDATION STATES-->
		<div class="portlet">
			<div class="portlet-title">
				<div class="caption">

					<i class="fa fa-gift"></i>Website management system <?php echo $this->serverUrl()?>
                    
                </div>
			</div>
			<div class="portlet-body form">
                <?php if (count($this->messages)) : ?>
                    <?php foreach ($this->messages as $message) : ?>
                        <div class="alert alert-success">
					<button class="close" data-close="alert"></button>
                            <?php echo $message; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <!-- BEGIN FORM-->
				<!-- END FORM-->
			</div>
			<!-- END VALIDATION STATES-->
		</div>
	</div>
</div>
