<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body id="home">
        <header>
            <?php echo $this->action('header-banner', 'index', 'default', Zend_Controller_Front::getInstance()->getRequest()->getParams())?>
        </header>
        <nav>
            <div id="gnav">
                <?php echo $this->action('nav', 'index', 'default', Zend_Controller_Front::getInstance()->getRequest()->getParams())?>
            </div>
            <!--#gnav-->
        </nav>
        <div id="mainVisual">
            <img src="<?php echo $this->baseUrl('css/images')?>/main01.png" alt="">
        </div>
        <!--#mainVisual-->
        <div id="contents" class="clearfix">
            <div id="main">
                <?php echo $this->layout()->content;?>
            </div>
            <!--#main-->
            <div id="sidebar">
                <nav>
                    <div id="subNav">
                        <?php echo $this->action('category', 'index', 'default', Zend_Controller_Front::getInstance()->getRequest()->getParams())?>
                    </div>
                    <!--#subNav-->
                </nav>
                <div class="conSide01">
                    <a href="#/contact.php"><img src="<?php echo $this->baseUrl('css/images')?>/sideBan01.jpg" alt=""></a>
                </div>
                <!--.conSide01-->
                <div class="conSide01">
                    <a href="#/contact.php"><img src="<?php echo $this->baseUrl('css/images')?>/sideBan03.jpg" alt=""></a>
                </div>
                <!--.conSide01-->
                <div class="conSide01 about">
                    <?php echo $this->action('about', 'index', 'default', Zend_Controller_Front::getInstance()->getRequest()->getParams())?>
                </div>
                <!--.conSide01-->
            </div>
            <!--#sidebar-->
        </div>
        <!--#contents-->
        <div id="topLink">
            <a href="#header">▲ ページの先頭へ</a>
        </div>
        <footer>
            <div id="footer">
                <div id="footerInner">
                    <ul class="clearfix">
                        <li><a href="<?php echo $this->baseUrl('/')?>">ホーム</a></li>
                        <li class="second"><a href="<?php echo $this->baseUrl('model/index')?>">サンプル</a></li>
                        <li><a href="<?php echo $this->baseUrl('product/index')?>">取り扱い商品</a></li>
                        <li><a href="<?php echo $this->baseUrl('payment/index')?>">お支払い・送料</a></li>
                        <li><a href="<?php echo $this->baseUrl('company/index')?>">工場ご紹介</a></li>
                        <li><a href="<?php echo $this->baseUrl('new/index')?>">ニュース</a></li>
                        <li><a href="<?php echo $this->baseUrl('contact/index')?>">お問い合せ</a></li>
                    </ul>
                </div>
                <!--#footerInner-->
            </div>
            <!--#footer-->
        </footer>
        <?php echo $this->headScript(); ?>
        <?php echo Common_Debug::printSqlHtml()?>
    </body>
</html>