<div id="header" class="clearfix">
    <h1><a href="<?php echo $this->baseUrl('/')?>"><img src="<?php echo $this->baseUrl('css/images')?>/h1.png" alt="業務用おしぼり販売のニチヨー株式会社"></a></h1>
    <div id="headerInfo01">おしぼりタオル、布おしぼり、紙おしぼりなどを販売する業務用おしぼり専門店です。その他、タオルなど業務用消耗品も取り扱っています。</div>
    <ul class="clearfix">
        <li><img src="<?php echo $this->baseUrl('css/images')?>/headerImg01.png" alt="即日出荷※一部商品除く"></li>
        <li><img src="<?php echo $this->baseUrl('css/images')?>/headerImg02.png" alt="送料無料※一部地域を除く"></li>
    </ul>
    <div id="headerInfo02">
        <img src="<?php echo $this->baseUrl('css/images')?>/headerImg03.png" alt="【お電話でお問い合わせ】06-6435-2400 受付時間：平日9：00～18：00">
    </div>
</div>
<!--#header-->