<div class="con01 clearfix">
                    <div>
                        【業務用おしぼり、フェイスタオル、バスタオルの専門店】<br>
                        おしぼりタオル、布おしぼり、紙おしぼりなどを販売する業務用おしぼり専門店です。その他、タオルなど業務用消耗品も取り扱っています。
                    </div>
                </div>
                <!--.con01-->
        <div class="con04">
            <h3 class="tit02">当社おしぼりはベトナムより輸入した良質なおしぼりです！</h3>
            <div class="clearfix">
                <p>・飲食店等一般業務用として幅広くご利用いただいている商品です。<br>
                    ・全国のリース業者が使用している耐久性に優れた業務用おしぼりです。<br>
                    ・昔から日本全国定番のおしぼりの種類です。
                </p>
                <p>当社はベトナムより輸入した良質なおしぼりやタオルを全国のリネン・リース業者、大型施設（ホテル、ゴルフ場、介護施設、自治体等）に販売しており、豊富なバリエーションと低価格でご好評いただいております。<br>
                    もともとおしぼりは中国製よりベトナム製の方が多く流通している商品です。ベトナム製は縫製がしっかりしており、中国製に比べ全体にムラがありません。
                </p>
                <img src="<?php echo $this->baseUrl('css/images')?>/img01.jpg" alt="">
            </div>
            <!--.clearfix-->
            <ul class="clearfix">
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img02.jpg" alt=""></li>
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img03.jpg" alt=""></li>
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img04.jpg" alt=""></li>
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img05.jpg" alt=""></li>
            </ul>
            <!--.clearfix-->
        </div>
        <!--.con04-->
        <div class="con03">
            <h3 class="tit02">商品ご購入のお客様はこちら</h3>
            <ul class="prodList clearfix">
                <li>
                    <h4>おしぼりタオル／白</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod01.png" alt="">
                    <p>飲食店等で幅広くご利用頂いている耐久性に優れた業務用おしぼり</p>
                </li>
                <li>
                    <h4>おしぼりタオル／カラー</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod02.png" alt="">
                    <p>店舗の雰囲気や料理に合わせて選べるカラーの業務用おしぼり</p>
                </li>
                <li>
                    <h4>おしぼりトレイ</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod03.png" alt="">
                    <p>清潔感があり、テーブルに映えるステレンス製のおしぼりトレイ</p>
                </li>
                <li>
                    <h4>おしぼり用温冷庫</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod04.png" alt="">
                    <p>インテリアと調和するデザイン＆親切設計のおしぼり温冷庫</p>
                </li>
                <li>
                    <h4>紙おしぼり</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod05.png" alt="">
                    <p>肌触りがよく、破れにくく、使い勝手がよい上質な紙おしぼり</p>
                </li>
                <li>
                    <h4>フェイスタオル</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod06.png" alt="">
                    <p>様々な用途に使えるふんわりとしたフェイスタオル（白・カラー）</p>
                </li>
                <li>
                    <h4>バスタオル</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod07.png" alt="">
                    <p>綿100％で吸水性が高く、ふんわりとした質感の高品質なバスタオル</p>
                </li>
                <li>
                    <h4>訳あり在庫処分品</h4>
                    <img src="<?php echo $this->baseUrl('css/images')?>/prod08.png" alt="">
                    <p>ペーパータオルやティッシュペーパー、高級割り箸などを特別価格で</p>
                </li>
            </ul>
            <!--.prodList-->
        </div>
        <!--.con03-->
        <div class="con05">
            <h3 class="tit02">その他の取り扱い商品</h3>
            <div class="clearfix">
                <div>
                    <p>業務用おしぼり以外にも、下記のように幅広い商品を取り扱っておりますので、メールや電話など、お気軽にお問い合わせください。</p>
                    <p>タオル／石鹸・洗剤／紙類／介護用品・衛生用品／家庭用品</p>
                    <a href="#/products.php">＞ 詳しくはこちら</a>
                </div>
                <img src="<?php echo $this->baseUrl('css/images')?>/img06.jpg" alt="">
            </div>
            <!--.clerafix-->
        </div>
        <!--.con05-->
        <div class="con02">
            <iframe src="<?php echo $this->baseUrl('css/images')?>/likebox.html" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:740px; height:395px;" allowtransparency="true"></iframe>
        </div>
        <!--.con02-->