<div class="con01 clearfix">
                    <div>
                        【業務用おしぼり、フェイスタオル、バスタオルの専門店】<br>
                        おしぼりタオル、布おしぼり、紙おしぼりなどを販売する業務用おしぼり専門店です。その他、タオルなど業務用消耗品も取り扱っています。
                    </div>
                </div>
                <!--.con01-->
        <div class="con04">
            <h3 class="tit02">当社おしぼりはベトナムより輸入した良質なおしぼりです！</h3>
            <div class="clearfix">
                <p>・飲食店等一般業務用として幅広くご利用いただいている商品です。<br>
                    ・全国のリース業者が使用している耐久性に優れた業務用おしぼりです。<br>
                    ・昔から日本全国定番のおしぼりの種類です。
                </p>
                <p>当社はベトナムより輸入した良質なおしぼりやタオルを全国のリネン・リース業者、大型施設（ホテル、ゴルフ場、介護施設、自治体等）に販売しており、豊富なバリエーションと低価格でご好評いただいております。<br>
                    もともとおしぼりは中国製よりベトナム製の方が多く流通している商品です。ベトナム製は縫製がしっかりしており、中国製に比べ全体にムラがありません。
                </p>
                <img src="<?php echo $this->baseUrl('css/images')?>/img01.jpg" alt="">
            </div>
            <!--.clearfix-->
            <ul class="clearfix">
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img02.jpg" alt=""></li>
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img03.jpg" alt=""></li>
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img04.jpg" alt=""></li>
                <li><img src="<?php echo $this->baseUrl('css/images')?>/img05.jpg" alt=""></li>
            </ul>
            <!--.clearfix-->
        </div>
        <!--.con04-->
        <div class="con03">
            <h3 class="tit02">商品ご購入のお客様はこちら</h3>
            <ul class="prodList clearfix">
                <?php foreach ($this->newProduct as $key => $value):?>
                    <li>
                        <img width="180" src="<?php echo $value['image_preview']?>" alt="<?php echo $value['product_name']?>" title="<?php echo $value['product_name']?>">
                        <h4><a href="<?php echo $this->baseUrl('product/detail/id/'.$value['id'])?>" title="<?php echo $value['product_name']?>"><?php echo $value['product_name']?></a></h4>
                    </li>
                <?php endforeach;?>
            </ul>
            <!--.prodList-->
        </div>
