<div class="contact">
	<div class="company">
		<h2><?php echo $this->lang['company_name']?></h2>
	</div>
	<div class="company-address">
		Địa chỉ: <b><?php echo $this->lang['company_address']?></b>
	</div>
	<div class="company-email">
		Email: <a
			href="mailto:<?php echo $this->lang['company_mail']?>?Subject=<?php echo $this->lang['mail_subject']?>"
			target="_top"><?php echo $this->lang['company_mail']?></a>
	</div>
	<div class="company-phone">
		Điện thoại: <b><?php echo $this->lang['company_phone']?></b>
	</div>
	<div class="map">
		<iframe
			src="https://www.google.com/maps/d/embed?mid=zcjmlwtFDuQE.kQWzZEW0rVEk"
			width="100%" height="480"></iframe>
	</div>
</div>