<div class="row">
	<div class="col-md-12">
		<!-- BEGIN VALIDATION STATES-->
		<div class="portlet">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><?php if(empty($this->id)):?>Tạo mới tin tức<?php else:?>Edit news # <?php echo $this->id;?><?php endif;?>
                </div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form action="<?php echo $this->baseUrl('admin/tin-tuc/save')?>"
					id="admin_form" class="form-horizontal" method="POST"
					enctype="multipart/form-data">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
							You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
							Your form validation is successful!
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Title <span
								class="required"> * </span>
							</label>
							<div class="col-md-4">
                                <?php echo $this->form->getElement('title')?>
                            </div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Content summary </label>
							<div class="col-md-5">
                                <?php echo $this->form->getElement('summary')?>
                            </div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Content </label>
							<div class="col-md-8">
                                <?php echo $this->form->getElement('body')?>
                            </div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Current image </label>
							<div class="col-md-4">
								<a class="fancybox-image"
									href="<?php echo $this->data['image_path']?>"><img
									src="<?php echo $this->data['image_path_preview']?>"
									alt="<?php echo $this->data['title']?>" width="100" /></a>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">News image </label>
							<div class="col-md-4">
								<input type="file" name="image" />

							</div>
						</div>

						<input type="hidden" name="id" value="<?php echo $this->id?>" /> <input
							type="hidden" name="image_old"
							value="<?php echo $this->data['image']?>" />
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<input type="hidden" name="access_redirect" value=""
									id="access_redirect" />
								<button type="submit" class="btn green" id="save">Save</button>
								<button type="submit" class="btn btn-info" id="save_and_close">Save and close</button>
								<button type="button" class="btn default"
									data-url="<?php echo $this->baseUrl('admin/tin-tuc/index')?>"
									id="btn_cancel">Cancel</button>
							</div>
						</div>
					</div>
				</form>
				<!-- END FORM-->
			</div>
			<!-- END VALIDATION STATES-->
		</div>
	</div>
</div>
