<div id="fb-root"></div>
<script>
	(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>
<div class="product_detail">
	<div class="button-share">
		<div class="fb-like" data-href="<?php echo $this->urlShare?>"
			data-layout="standard" data-action="like" data-show-faces="true"
			data-share="true"></div>
	</div>
	<div class="image">
		<img src="<?php echo $this->data['image_path_preview']?>"
			alt="<?php echo $this->data['title']?>" width="250"
			title="<?php echo $this->data['image_path_preview']?>">
	</div>
	<div class="title pd10">
		<?php echo $this->data['title']?>
	</div>
	<div class="price pd10">
		Tình trạng: <span class="red"><?php if ($this->data['status'] == 1){?>Còn hàng<?php } else {?>Hết hàng<?php }?></span>
	</div>
	<?php if ($this->data['price'] != '' && $this->data['price'] != 0) {?>
		<?php if ($this->data['price_promotion'] != '' && $this->data['price_promotion'] != 0):?>
			<div class="price pd10 price_start">
				Giá: <?php echo $this->data['price']?>
			</div>
		<?php endif;?>
		<?php if ($this->data['price_promotion'] != '' && $this->data['price_promotion'] != 0) {?>
			<div class="price pd10 price_prome">
				KM: <?php echo $this->data['price_promotion']?>
			</div>
		<?php } else {?>
			<div class="price pd10 price_prome">
				Giá: <?php echo $this->data['price']?>
			</div>
		<?php }?>
	<?php } else {?>
		<div class="price pd10">
			Giá: Liên hệ <?php echo $this->lang['company_phone']?>
		</div>
	<?php }?>
	<div class="price pd10">
		Thương hiệu: <span class="red"><?php echo $this->data['brand_name']?></span>
	</div>
	<div class="price pd10">
		Bảo hành: <span class="red"><?php echo $this->data['bao_hanh']?></span>
	</div>
	<?php if ($this->data['promotion'] != ''):?>
		<div class="km pd10">
		Quà tặng: <span class="red"><?php echo $this->data['promotion']?></span>
	</div>
	<?php endif;?>
	<div class="phone_order">
		<?php echo $this->lang['order_text']?>
	</div>
	<div class="area">Thông số kỹ thuật</div>
	<div class="technical-info">
		<?php echo $this->data['technical_info']?>
	</div>
	<div class="area">Đặc điểm sản phẩm</div>
	<div class="detail-product">
		<?php echo $this->data['body']?>
	</div>
	<div class="area">Chúng tôi trên facebook</div>
	<div class="share-product">
		<div class="share-product-page">
			<div class="fb-page" data-href="<?php echo FANPAGE_FACEBOOK?>"
				data-width="310" data-height="500" data-small-header="true"
				data-adapt-container-width="true" data-hide-cover="true"
				data-show-facepile="true" data-show-posts="true">
				<div class="fb-xfbml-parse-ignore">
					<blockquote cite="<?php echo FANPAGE_FACEBOOK?>">
						<a href="<?php echo FANPAGE_FACEBOOK?>">
							<?php echo $this->lang['facebook_text']?>
						</a>
					</blockquote>
				</div>
			</div>
		</div>
	</div>
</div>