<!DOCTYPE HTML>
<html>
<head>
<title>404 Page not found</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="<?php echo $this->baseUrl('error/')?>css/style.css">
</head>
<body>
<div class="wrap">
<div class="main">
	<div class="banner">
		<img src="<?php echo $this->baseUrl('error/')?>images/banner.png" alt="" />
	</div>
	<div class="text">
	   <a class="home" href="<?php echo $this->baseUrl('/')?>">ホーム</a>
		<?php if ('development' == APPLICATION_ENV ): ?>
    	<div class="trace-message">
    		<h2 class="heading-lv1">
    			<?php echo $this->exception->getMessage()?>
    		</h2>
    		<h3>Stack trace:</h3>
    					<pre>
    			<?php echo $this->exception->getTraceAsString() ?> </pre>
    					<h3>Request Parameters:</h3>
    					<pre>
    			<?php var_dump($this->request->getParams()) ?> </pre>
    					<h3>Query:</h3>
    					<pre>
    			<?php echo Common_Debug::printSqlHtml()?> </pre>
    					<h3>Session Parameters:</h3>
    					<pre>
    			<?php var_dump(Common_Authentication::getUser()) ?> </pre>
	</div>

	<?php endif ?>
	</div>
</div>
<div class="footer">
	<?php echo $this->headScript(); ?>
    <?php echo Common_Debug::printSqlHtml()?>
</div>
</div>
</body>
</html>