<div class="row">
	<div class="col-md-12">
		<!-- BEGIN VALIDATION STATES-->
		<div class="portlet">
			<div class="portlet-title">
				<div class="caption">

					<i class="fa fa-gift"></i>Edit banner # <?php echo $this->id;?>
                    
                </div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form action="<?php echo $this->baseUrl('admin/slide/save')?>"
					id="admin_form" class="form-horizontal" method="POST"
					enctype="multipart/form-data">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
							You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
							Your form validation is successful!
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Title <span
								class="required"> * </span>
							</label>
							<div class="col-md-4">
                                <?php echo $this->form->getElement('title')?>
                            </div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Current banner </label>
							<div class="col-md-4">
								<a class="fancybox-image"
									href="<?php echo $this->data['image_path']?>"><img
									src="<?php echo $this->data['image_path_preview']?>"
									alt="<?php echo $this->data['title']?>" width="100" /></a>

							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">New banner </label>
							<div class="col-md-4">
								<input type="file" name="image" />

							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Link </label>
							<div class="col-md-4">
                                <?php echo $this->form->getElement('url')?>
                            </div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Status</label>
							<div class="col-md-4">
								<label class="control-label col-md-4">Active<input
									type="radio" <?php if ($this->data['type'] == 1):?>
									checked="checked" <?php endif;?> name="type" value="1" /></label>
								<label class="control-label col-md-4">Inactive<input type="radio"
									<?php if ($this->data['type'] == 0):?> checked="checked"
									<?php endif;?> name="type" value="0" /></label>
							</div>
						</div>
						<input type="hidden" name="id" value="<?php echo $this->id?>" /> <input
							type="hidden" name="image_old"
							value="<?php echo $this->data['image']?>" />
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<input type="hidden" name="access_redirect" value=""
									id="access_redirect" />
								<button type="submit" class="btn green" id="save">Save</button>
								<button type="submit" class="btn btn-info" id="save_and_close">Save and close</button>
								<button type="button" class="btn default"
									data-url="<?php echo $this->baseUrl('admin/slide/index')?>"
									id="btn_cancel">Cancel</button>
							</div>
						</div>
					</div>
				</form>
				<!-- END FORM-->
			</div>
			<!-- END VALIDATION STATES-->
		</div>
	</div>
</div>
